feat: removed send button
SCCapstone/DKMS pull request #233
Opened 2023-03-22 23:35 UTC by masondjoseph

#181 - removed the send button from feed items.

2023-03-22 23:48 UTC, claycrews2002 requested changes

2023-03-22 23:48 UTC, claycrews2002 commented on components/feed/FeedItem.tsx
>          <div className="flex flex-row justify-start items-center">
Probably want to remove the this flex-row div and the div around the like button since they're unused now.

2023-03-23 19:04 UTC, cravend approved these changes

2023-03-24 16:07 UTC, claycrews2002 approved these changes

2023-03-24 16:08 UTC, merged