feat: make music pages
SCCapstone/DKMS pull request #244
Opened 2023-03-24 19:00 UTC by cravend

Also closes #187

2023-03-24 23:03 UTC, claycrews2002 requested changes
Add hostname `**.spotifycdn.com` in next.config.js.

![Screenshot 2023-03-24 at 6 46 51 PM](https://user-images.githubusercontent.com/37126723/227658158-75eb95ab-083e-4fed-90a2-99a18d81b5e1.png)
![Screenshot 2023-03-24 at 6 47 07 PM](https://user-images.githubusercontent.com/37126723/227658166-d5b8b328-b21c-4921-9321-55078a3aec45.png)

---

When the "Open in Spotify" button is clicked the address isn't correct.

![Screenshot 2023-03-24 at 6 51 19 PM](https://user-images.githubusercontent.com/37126723/227658522-7d18f1d5-cae6-4244-aca2-6187e878aa80.png)

2023-03-25 14:30 UTC, claycrews2002 requested changes
![Screenshot 2023-03-25 at 10 24 37 AM](https://user-images.githubusercontent.com/37126723/227723291-2899f04f-0d21-4b7b-baa4-89621878bb15.png)

For listing the tracks, when there are multiple artists it only links to the main artist's page when clicked. In this image trying to get to Miguel will take me to Mac Miller's page.

2023-03-25 14:36 UTC, cravend commented
> ![Screenshot 2023-03-25 at 10 24 37 AM](https://user-images.githubusercontent.com/37126723/227723291-2899f04f-0d21-4b7b-baa4-89621878bb15.png)
> 
> For listing the tracks, when there are multiple artists it only links to the main artist's page when clicked. In this image trying to get to Miguel will take me to Mac Miller's page.

New issue made! #252

2023-03-25 14:41 UTC, claycrews2002 approved these changes

2023-03-25 14:42 UTC, merged