feat: see user's playlists
SCCapstone/DKMS pull request #284
Opened 2023-03-31 18:11 UTC by sophiecra

- feat: see user's playlist on profile page
- feat: maximum of 8 profiles

2023-04-01 17:05 UTC, claycrews2002 submitted a review, later dismissed

2023-04-01 17:06 UTC, cravend requested changes

2023-04-01 17:06 UTC, cravend commented on app/profile/[username]/page.tsx
> +      <div className="grid md:grid-cols-3 gap-4 pb-5">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/7117993/229304611-646333dd-9e88-48a5-bd98-d1f3786c1c33.png">
Too compact, just do it at the bottom. You can also get rid of the `!isCurrentUser` that hides the recommended tracks, that way it's balanced

2023-04-01 17:06 UTC, cravend commented on components/music/grids/PlaylistsGrid.tsx
> +      {" "}
can you delete this random spacec

2023-04-01 17:06 UTC, cravend commented on lib/getPlaylistsForUser.ts
> +import fetchServer from "./fetch/fetchServer";
use the `@/lib/fetch/fetchServer` import

2023-04-02 21:30 UTC, cravend approved these changes

2023-04-02 21:31 UTC, merged