feat: add queue to sidebar
SCCapstone/DKMS pull request #305
Opened 2023-04-02 22:34 UTC by cravend

2023-04-02 22:40 UTC, claycrews2002 requested changes
![Screenshot 2023-04-02 at 6 38 30 PM](https://user-images.githubusercontent.com/37126723/229382959-b729ddfe-0f0d-4a77-b07e-9b9a5a272d99.png)

I get this error, possibly related to being a non-premium user.

2023-04-03 01:19 UTC, sophiecra requested changes

2023-04-03 01:19 UTC, sophiecra commented on components/Sidebar/panels/Queue/index.tsx
> +        <p>Nothing is playing!</p>
<img width="260" alt="Screen Shot 2023-04-02 at 9 17 32 PM" src="https://user-images.githubusercontent.com/77420992/229390966-21f72ce4-32b3-4ea9-9c7f-8a314c9e2f04.png">

When Spotify has yet to connect no "Nothing is playing" message shows

2023-04-03 03:28 UTC, claycrews2002 approved these changes

2023-04-03 03:39 UTC, sophiecra approved these changes

2023-04-03 03:40 UTC, merged